### ISSUE TITLE
Default BLAST DB location

### ISSUE THREAD

**Issue by devindrown** [genomicsITER/NanoCLUST#18]
Should the default DB location be set to `/tmp/` as below?

https://github.com/genomicsITER/NanoCLUST/blob/26dc468faf8b4016bb61ed1648f5885378e8f5e2/main.nf#L430

When I manually specify the DB location at the command line and use the Docker profile, the '/tmp' is appended to my input and classification fails.

**Comment by genomicsITER** [comment]
Hi, thank you for opening the issue

Using BLAST databases along with the docker profile was kind of a challenge since the process run in an isolated environment and the database files have to be mounted before running the classification. 

All the content in the NanoCLUST dir (where the main.nf is stored) is automatically mounted in /tmp (following the nextflow docker options), so it is possible to access and run your DBs and other NanoCLUST files inside the docker container if they were stored in the NanoCLUST dir when the classification process start. 

Since this is a little bit tricky, we recommend to have the DB inside the NanoCLUST dir to ensure that it is mounted in the docker container. We know this can be problematic when using large DBs (not the case of NCBI 16S) stored in different locations. We are going to rethink this issue in order to provide a better solution.

You won't find this issue when running with the conda profile since ti doesn't create any environment with an isolated filesystem.

**Comment by devindrown** [comment]
Thank you for explaining this. I did have the DB inside the NanoCLUST dir as per the install instructions. I was only able to get the docker version to run by removing the hard coded /tmp/ location. Perhaps my Docker install isn't configured properly. 

In any case, I'm able to run the pipeline. This is a great piece of software.
