### ISSUE TITLE
#Cannot read project manifest

### ISSUE THREAD

**Issue by YulinzhangSia** [genomicsITER/NanoCLUST#6]
Hello!

I met a problem when I tried to use this pipeline to analyze my data.
The code typed is :
_nextflow run nf-core/nanoclust -profile conda --reads 'mergelength.fastq' --db "db/16S_ribosomal_RNA" --tax "db/taxdb/"_

While the system reported:
_N E X T F L O W  ~  version 20.04.1
Pulling nf-core/nanoclust ...
WARN: Cannot read project manifest -- Cause: Remote resource not found: https://api.github.com/repos/nf-core/nanoclust/contents/nextflow.config
Remote resource not found: https://api.github.com/repos/nf-core/nanoclust/contents/main.nf_

Is there something wrong?
Thanks!

**Comment by genomicsITER** [comment]
Hi

Thank you for your message. At this time Nanoclust is not added to the nf-core pipeline collection so the manifest will not be found if you execute the pipeline that way. The command should be executed like:
_nextflow run pathtonanoclust/main.nf [...]_
instead of using the _nf-core/nanoclust_ identifier.

We're fixing the main docs to point this out. Please contact if problems persist.
